import { ref } from "vue";
import { useWorkstationDashboard } from "./useWorkstationDashboard.js";

/**
 * Dashboard store binding.
 * Shares state with its sibling modules through the `w` context bag.
 */
export function useWorkstationDashboardBinding(w) {
  const { _minsOf, addDays, currentUser, filteredWorkBlocks, getLocalTodayISO, isDarkMode, isNonWorkingNature, isTracking, selectedEmployee, selectedProject, teamMembers, todayDate, todayISO, trackerBlockName, trackerBoundBlock } = w;

  // Dashboard Domain Store Integration
  const dashboardStore = useWorkstationDashboard({
    todayDate,
    filteredWorkBlocks,
    isTracking,
    trackerBlockName,
    trackerBoundBlock,
    isDarkMode,
    isNonWorkingNature,
    getLocalTodayISO,
    todayISO,
    addDays,
    _minsOf
  });
  const {
    selectedDashboardDate,
    dashboardWeekOffset,
    dashboardWeekDays,
    selectedDashboardDateLabel,
    pastBlocksHeading,
    pastDeliverablesStats,
    getBlockCardAccent,
    getBlockBadgeTheme,
    getBlockVarianceBadge,
    focusBlocksHeading,
    dashboardDayTitle,
    dashboardDaySummary,
    todayDirection,
    shiftDashboardWeek,
    selectDashboardDate,
    onDashboardDayKey,
    resetDashboardToToday,
    formatAmPm,
    formatBlockRange,
    getMeetUrl,
    getBlockTimingInfo,
    dayFocusBlocks,
    awayFocusBlocks,
    workFocusBlocks,
    activeOrCurrentBlocks,
    untrackedCurrentBlocks,
    upNextBlock,
    isBlockInNow,
    isBlockConcluded,
    isBlockCompleted,
    getStartsInText,
    upcomingFocusBlocks,
    pastFocusBlocks,
    showAllPastBlocks,
    visiblePastFocusBlocks,
    remainingPastBlocksCount,
    concludedRovingRow,
    concludedRovingCol,
    canBlockReopen,
    hasBlockExpandableNotes,
    getConcludedNotesCol,
    getMaxConcludedCol,
    setConcludedRoving,
    concludedTabindex,
    focusConcludedCell,
    onConcludedGridKey,
    toggleShowAllPastBlocks,
    expandedBlockNotes,
    isBlockNotesExpanded,
    toggleBlockNotes,
    isLongNote,
    dashboardKPIs,
    updateDashboardKPIs,
    paciPlannedHours,
    paciUnplannedHours,
    paciNonWorkingHours,
    paciRatio,
    totalFilteredHours,
    _blockEffectiveStartMins,
    _byTimeDesc,
    _byTimeAsc
  } = dashboardStore;
  // Kept under this name for the keyboard shortcut and the header menu; it is the one plan dialog
  const openNewTaskModal = (initialDate = null) => {
    // `@click="openNewTaskModal"` passes the MouseEvent here; only a YYYY-MM-DD string is a date
    const explicit = typeof initialDate === 'string' ? initialDate : null;
    w.workBlockStore.openPlanDialog({ date: explicit || selectedDashboardDate.value || todayDate.value });
  };

  Object.assign(w, {
    selectedDashboardDate,
    dashboardWeekOffset,
    dashboardWeekDays,
    selectedDashboardDateLabel,
    pastBlocksHeading,
    pastDeliverablesStats,
    getBlockCardAccent,
    getBlockBadgeTheme,
    getBlockVarianceBadge,
    focusBlocksHeading,
    dashboardDayTitle,
    dashboardDaySummary,
    todayDirection,
    shiftDashboardWeek,
    selectDashboardDate,
    onDashboardDayKey,
    resetDashboardToToday,
    formatAmPm,
    formatBlockRange,
    getMeetUrl,
    getBlockTimingInfo,
    dayFocusBlocks,
    awayFocusBlocks,
    workFocusBlocks,
    activeOrCurrentBlocks,
    untrackedCurrentBlocks,
    upNextBlock,
    isBlockInNow,
    isBlockConcluded,
    isBlockCompleted,
    getStartsInText,
    upcomingFocusBlocks,
    pastFocusBlocks,
    showAllPastBlocks,
    visiblePastFocusBlocks,
    remainingPastBlocksCount,
    concludedRovingRow,
    concludedRovingCol,
    canBlockReopen,
    hasBlockExpandableNotes,
    getConcludedNotesCol,
    getMaxConcludedCol,
    setConcludedRoving,
    concludedTabindex,
    focusConcludedCell,
    onConcludedGridKey,
    toggleShowAllPastBlocks,
    expandedBlockNotes,
    isBlockNotesExpanded,
    toggleBlockNotes,
    isLongNote,
    dashboardKPIs,
    updateDashboardKPIs,
    paciPlannedHours,
    paciUnplannedHours,
    paciNonWorkingHours,
    paciRatio,
    totalFilteredHours,
    openNewTaskModal,
  });
}
